### ISSUE TITLE
Add Error Email Logic

### ISSUE THREAD

**Issue by cdconn00** [Aggie-Web-Developers/awd-website#147]
Add a routine that sends an error email to our Gmail whenever a site error occurs. Modify our error handling logic to utilize console.error instead of console.log or whatever else we are doing

**Acceptance Criteria**
When any error happens on the site, it should be logged to console.error.
Then, the console.error routine should be overridden to send an error email to aggiedevelopers@gmail.com.

**Comment by cdconn00** [comment]
https://stackoverflow.com/questions/7204474/how-do-i-send-an-email-for-every-error-that-occurs-in-node-js

**Comment by Unit404** [comment]
accidentally closed the issue :(

Unsure if this is the right place to ask this but what counts as an 'error'? Would it just be in any .catch(...) call a function that sends the error message in an email?

**Comment by cdconn00** [comment]
Good question! For right now, yeah let's use the catch statements as the places where the errors occur.
